// src/lib/api/errorCodes.ts
// 统一错误码定义（前后端约定）

export const ERROR_CODES = {
  // 认证相关
  AUTH_EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  AUTH_INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  AUTH_REFRESH_FAILED: 'REFRESH_FAILED',

  // 业务相关
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_CONFLICT: 'PROJECT_CONFLICT',
  PROJECT_INVALID_STATUS: 'PROJECT_INVALID_STATUS',

  CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND',
  CHARACTER_DUPLICATE: 'CHARACTER_DUPLICATE',

  MODEL_NOT_FOUND: 'MODEL_NOT_FOUND',
  MODEL_UNAVAILABLE: 'MODEL_UNAVAILABLE',

  // 请求相关
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // 通用
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && Object.values(ERROR_CODES).includes(value as ErrorCode);
}