/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目详情（含 steps / characters） */
        get: operations["getProjectDetail"];
        /** 更新项目（含绑定工作流 workflowId） */
        put: operations["updateProject"];
        post?: never;
        /** 删除项目 */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/steps/{stepId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
                stepId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 保存某步正文 */
        put: operations["saveStepEdit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认某步 */
        post: operations["confirmStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发项目生成（SSE / 流式，后端就绪时启用） */
        post: operations["generateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色列表 */
        get: operations["listCharacters"];
        put?: never;
        /** 创建角色 */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /** 获取角色详情 */
        get: operations["getCharacterDetail"];
        /** 更新角色 */
        put: operations["updateCharacter"];
        post?: never;
        /** 删除角色 */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传角色头像 */
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /** 获取角色对话历史 */
        get: operations["listCharacterMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 角色对话（SSE / 流式） */
        post: operations["chatWithCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取可用创作流水线 */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Project: {
            id: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "generating" | "completed" | "paused";
            genre?: string;
            description?: string;
            pinned?: boolean;
            workflowId?: string;
            createdAt: string;
            updatedAt: string;
        };
        ProjectListResponse: {
            projects: components["schemas"]["Project"][];
        };
        ProjectResponse: {
            project: components["schemas"]["Project"];
            version?: number;
        };
        ProjectDetail: {
            project: components["schemas"]["Project"];
            steps: components["schemas"]["Step"][];
            characters?: {
                id?: string;
                name?: string;
                description?: string;
            }[];
        };
        Step: {
            id: string;
            agent: string;
            agentName?: string;
            content: string;
            status: string;
            nodeId?: string;
        };
        StepsResponse: {
            steps: components["schemas"]["Step"][];
        };
        CreateProjectRequest: {
            title: string;
            description: string;
            genre: string;
            version?: number;
        };
        Character: {
            id: string;
            name: string;
            avatar?: string;
            aliases?: string[] | null;
            description: string;
            role?: string;
            status?: string;
            currentProfile?: string;
            customRole?: string;
            relationships?: {
                id: string;
                targetId: string;
                relation: string;
            }[] | null;
            projectId?: string | null;
            images?: string[];
            referenceImages?: string[] | null;
            referenceImage?: string | null;
            imageSeed?: number | null;
            createdAt: string;
        };
        CharactersResponse: {
            characters: components["schemas"]["Character"][];
        };
        CharacterResponse: {
            character: components["schemas"]["Character"];
        };
        CreateCharacterRequest: {
            name: string;
            description: string;
            projectId?: string | null;
            avatar?: string;
        };
        UpdateCharacterRequest: {
            name?: string;
            description?: string;
            avatar?: string;
            images?: string[];
            role?: string;
            customRole?: string;
            status?: string;
            currentProfile?: string;
            relationships?: {
                id: string;
                targetId: string;
                relation: string;
            }[] | null;
            referenceImages?: string[] | null;
            imageSeed?: number | null;
        };
        AvatarResponse: {
            avatar_url?: string;
            url?: string;
            avatar?: string;
        };
        Message: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        MessagesResponse: {
            messages: components["schemas"]["Message"][];
        };
        ChatMessageRequest: {
            message: string;
            project_id?: string;
            brief?: string;
            character_name?: string;
            character_description?: string;
            messages?: components["schemas"]["Message"][];
        };
        WorkflowSummary: {
            id: string;
            name: string;
            description?: string;
        };
    };
    responses: never;
    parameters: {
        ProjectId: string;
        CharacterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    getProjectDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    workflowId?: string;
                    title?: string;
                    description?: string;
                    genre?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveStepEdit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
                stepId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description 保存成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    step_id: string;
                };
            };
        };
        responses: {
            /** @description 确认成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    workflowId?: string;
                };
            };
        };
        responses: {
            /** @description 生成结果（或 SSE 流） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepsResponse"];
                };
            };
        };
    };
    listCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharactersResponse"];
                };
            };
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    getCharacterDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCharacterRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 头像地址 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarResponse"];
                };
            };
        };
    };
    listCharacterMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
        };
    };
    chatWithCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description 对话响应（或 SSE 流） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工作流列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflows?: components["schemas"]["WorkflowSummary"][];
                    };
                };
            };
        };
    };
}
