/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取项目列表 */
        get: operations["listProjects"];
        put?: never;
        /** 创建项目 */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** 获取项目详情（含 steps / characters） */
        get: operations["getProjectDetail"];
        /** 更新项目（含绑定工作流 workflowId） */
        put: operations["updateProject"];
        post?: never;
        /** 删除项目 */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/steps/{stepId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
                stepId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 保存某步正文 */
        put: operations["saveStepEdit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认某步 */
        post: operations["confirmStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 触发项目生成（SSE / 流式，后端就绪时启用） */
        post: operations["generateProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交图像生成任务（AI 绘画 / 角色立绘 / 章节插图） */
        post: operations["generateImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/video/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 提交视频生成任务（章节动画 / 预告片 / 角色卡动画） */
        post: operations["generateVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 同步用户模型配置（全量覆盖）。后端以 model.id 为主键落库；生成请求只需带 model_id，后端凭 id 取 adapter/baseUrl/apiKey/category/modalities/tier */
        put: operations["putUserModels"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色列表 */
        get: operations["listCharacters"];
        put?: never;
        /** 创建角色 */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /** 获取角色详情 */
        get: operations["getCharacterDetail"];
        /** 更新角色 */
        put: operations["updateCharacter"];
        post?: never;
        /** 删除角色 */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传角色头像 */
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        /** 获取角色对话历史 */
        get: operations["listCharacterMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 角色对话（SSE / 流式） */
        post: operations["chatWithCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取可用创作流水线 */
        get: operations["listWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Project: {
            id: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "generating" | "completed" | "paused";
            genre?: string;
            description?: string;
            pinned?: boolean;
            workflowId?: string;
            createdAt: string;
            updatedAt: string;
        };
        ProjectListResponse: {
            projects: components["schemas"]["Project"][];
        };
        ProjectResponse: {
            project: components["schemas"]["Project"];
            version?: number;
        };
        ProjectDetail: {
            project: components["schemas"]["Project"];
            steps: components["schemas"]["Step"][];
            characters?: {
                id?: string;
                name?: string;
                description?: string;
            }[];
        };
        Step: {
            id: string;
            agent: string;
            agentName?: string;
            content: string;
            status: string;
            nodeId?: string;
        };
        StepsResponse: {
            steps: components["schemas"]["Step"][];
        };
        CreateProjectRequest: {
            title: string;
            description: string;
            genre: string;
            version?: number;
        };
        Character: {
            id: string;
            name: string;
            avatar?: string;
            aliases?: string[] | null;
            description: string;
            role?: string;
            status?: string;
            currentProfile?: string;
            customRole?: string;
            relationships?: {
                id: string;
                targetId: string;
                relation: string;
            }[] | null;
            projectId?: string | null;
            images?: string[];
            referenceImages?: string[] | null;
            referenceImage?: string | null;
            imageSeed?: number | null;
            createdAt: string;
        };
        CharactersResponse: {
            characters: components["schemas"]["Character"][];
        };
        CharacterResponse: {
            character: components["schemas"]["Character"];
        };
        CreateCharacterRequest: {
            name: string;
            description: string;
            projectId?: string | null;
            avatar?: string;
        };
        UpdateCharacterRequest: {
            name?: string;
            description?: string;
            avatar?: string;
            images?: string[];
            role?: string;
            customRole?: string;
            status?: string;
            currentProfile?: string;
            relationships?: {
                id: string;
                targetId: string;
                relation: string;
            }[] | null;
            referenceImages?: string[] | null;
            imageSeed?: number | null;
        };
        AvatarResponse: {
            avatar_url?: string;
            url?: string;
            avatar?: string;
        };
        Message: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        MessagesResponse: {
            messages: components["schemas"]["Message"][];
        };
        ChatMessageRequest: {
            message: string;
            project_id?: string;
            brief?: string;
            character_name?: string;
            character_description?: string;
            messages?: components["schemas"]["Message"][];
        };
        WorkflowSummary: {
            id: string;
            name: string;
            description?: string;
        };
        ImageGenerationRequest: {
            prompt: string;
            negative_prompt?: string;
            /** @description 视觉模型 id（用户模型库主键，category:vision）；后端凭 id 取 adapter/baseUrl/apiKey */
            model_id?: string;
            project_id?: string;
            style?: string;
            size?: string;
            count?: number;
            characterId?: string;
            reference_images?: string[];
            seed?: number;
            source_step?: string;
            character_ids?: string[];
            context?: components["schemas"]["GenerationContext"];
        };
        VideoGenerationRequest: {
            prompt: string;
            /** @description 视觉模型 id（用户模型库主键，category:vision）；后端凭 id 取 adapter/baseUrl/apiKey */
            model_id?: string;
            project_id?: string;
            duration?: number;
            aspect?: string;
            reference_images?: string[];
            chapter_id?: string;
            character_ids?: string[];
            storyboard?: string;
            context?: components["schemas"]["GenerationContext"];
        };
        MediaTaskResponse: {
            task?: components["schemas"]["MediaTask"];
        };
        MediaTask: {
            id: string;
            prompt: string;
            /** @enum {string} */
            status: "pending" | "processing" | "completed" | "failed";
            progress?: number;
            result_url?: string;
            /** @enum {string} */
            kind: "image" | "video";
            project_id?: string;
            /** @enum {string} */
            source?: "character" | "chapter";
            source_ref?: string;
            chapter_id?: string;
            character_ids?: string[];
            storyboard?: string;
            createdAt: string;
        };
        GenerationContextCharacterRelation: {
            target: string;
            relation: string;
        };
        GenerationContextCharacter: {
            name: string;
            role?: string;
            description: string;
            currentProfile?: string;
            status: string;
            change?: string;
            relationships?: components["schemas"]["GenerationContextCharacterRelation"][] | null;
        };
        GenerationContext: {
            project_id?: string;
            project_title?: string;
            summary?: string;
            plot_summary?: string;
            characters?: components["schemas"]["GenerationContextCharacter"][] | null;
            outline?: string;
            outlineTree?: Record<string, never>[] | null;
            sections?: {
                title?: string;
                content?: string;
            }[] | null;
            /** @enum {string} */
            source?: "character" | "chapter";
            source_ref?: string;
            brief?: string;
            rag_chunks?: Record<string, never>[] | null;
        };
        UserModelConfig: {
            /** @description 模型主键（前端 uid），即生成请求携带的 model_id */
            id: string;
            name: string;
            /** @enum {string} */
            category: "llm" | "vision" | "omni" | "speech" | "embedding";
            /** @enum {string} */
            deployment?: "cloud" | "local";
            vendor: string;
            /** @description 后端据此选择调用库（openai/anthropic/kling/...） */
            adapter: string;
            baseUrl?: string;
            /** @description 前端 PUT 同步后由后端保管；前端本地不长期留存明文 */
            apiKey?: string;
            /** @description 实际传给厂商的模型名 */
            modelId: string;
            isDefault?: boolean;
            modalities?: ("image" | "video")[];
            auxiliary?: Record<string, never>[] | null;
        };
    };
    responses: never;
    parameters: {
        ProjectId: string;
        CharacterId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    getProjectDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 项目详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    workflowId?: string;
                    title?: string;
                    description?: string;
                    genre?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveStepEdit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
                stepId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description 保存成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    step_id: string;
                };
            };
        };
        responses: {
            /** @description 确认成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    workflowId?: string;
                    /** @description 正文生成语言模型 id（用户模型库主键）；后端凭 id 查 adapter/baseUrl/apiKey/category/tier */
                    model_id?: string;
                    /** @enum {string} */
                    category?: "llm" | "vision" | "omni" | "speech" | "embedding";
                };
            };
        };
        responses: {
            /** @description 生成结果（或 SSE 流） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepsResponse"];
                };
            };
        };
    };
    generateImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageGenerationRequest"];
            };
        };
        responses: {
            /** @description 已提交任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTaskResponse"];
                };
            };
            /** @description 任务受理（异步轮询） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTaskResponse"];
                };
            };
        };
    };
    generateVideo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoGenerationRequest"];
            };
        };
        responses: {
            /** @description 已提交任务 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTaskResponse"];
                };
            };
            /** @description 任务受理（异步轮询） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaTaskResponse"];
                };
            };
        };
    };
    putUserModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    models: components["schemas"]["UserModelConfig"][];
                };
            };
        };
        responses: {
            /** @description 同步成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: number;
                    };
                };
            };
        };
    };
    listCharacters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharactersResponse"];
                };
            };
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    getCharacterDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    updateCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCharacterRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 头像地址 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarResponse"];
                };
            };
        };
    };
    listCharacterMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 消息列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
        };
    };
    chatWithCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description 对话响应（或 SSE 流） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工作流列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        workflows?: components["schemas"]["WorkflowSummary"][];
                    };
                };
            };
        };
    };
}
